/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SampleRouteImport } from './routes/sample'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokuenInfoTermsAndConditionsRouteImport } from './routes/tokuen-info/terms-and-conditions'
import { Route as TokuenInfoPrivacyPolicyRouteImport } from './routes/tokuen-info/privacy-policy'

const SampleRoute = SampleRouteImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokuenInfoTermsAndConditionsRoute =
  TokuenInfoTermsAndConditionsRouteImport.update({
    id: '/tokuen-info/terms-and-conditions',
    path: '/tokuen-info/terms-and-conditions',
    getParentRoute: () => rootRouteImport,
  } as any)
const TokuenInfoPrivacyPolicyRoute = TokuenInfoPrivacyPolicyRouteImport.update({
  id: '/tokuen-info/privacy-policy',
  path: '/tokuen-info/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sample': typeof SampleRoute
  '/tokuen-info/privacy-policy': typeof TokuenInfoPrivacyPolicyRoute
  '/tokuen-info/terms-and-conditions': typeof TokuenInfoTermsAndConditionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sample': typeof SampleRoute
  '/tokuen-info/privacy-policy': typeof TokuenInfoPrivacyPolicyRoute
  '/tokuen-info/terms-and-conditions': typeof TokuenInfoTermsAndConditionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sample': typeof SampleRoute
  '/tokuen-info/privacy-policy': typeof TokuenInfoPrivacyPolicyRoute
  '/tokuen-info/terms-and-conditions': typeof TokuenInfoTermsAndConditionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sample'
    | '/tokuen-info/privacy-policy'
    | '/tokuen-info/terms-and-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sample'
    | '/tokuen-info/privacy-policy'
    | '/tokuen-info/terms-and-conditions'
  id:
    | '__root__'
    | '/'
    | '/sample'
    | '/tokuen-info/privacy-policy'
    | '/tokuen-info/terms-and-conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SampleRoute: typeof SampleRoute
  TokuenInfoPrivacyPolicyRoute: typeof TokuenInfoPrivacyPolicyRoute
  TokuenInfoTermsAndConditionsRoute: typeof TokuenInfoTermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sample': {
      id: '/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof SampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokuen-info/terms-and-conditions': {
      id: '/tokuen-info/terms-and-conditions'
      path: '/tokuen-info/terms-and-conditions'
      fullPath: '/tokuen-info/terms-and-conditions'
      preLoaderRoute: typeof TokuenInfoTermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokuen-info/privacy-policy': {
      id: '/tokuen-info/privacy-policy'
      path: '/tokuen-info/privacy-policy'
      fullPath: '/tokuen-info/privacy-policy'
      preLoaderRoute: typeof TokuenInfoPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SampleRoute: SampleRoute,
  TokuenInfoPrivacyPolicyRoute: TokuenInfoPrivacyPolicyRoute,
  TokuenInfoTermsAndConditionsRoute: TokuenInfoTermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
